language: python

python:
  - 2.7

env:
  - PATH: /opt/texbin:$PATH

before_install:
  - python travis_pre.py

install:
  - git clone https://github.com/scottkosty/install-tl-ubuntu.git
  - cp ./.nmc.profile install-tl-ubuntu/
  - cd install-tl-ubuntu
  - sudo ./install-tl-ubuntu -profile .nmc.profile
  - cd ..
  - sudo /opt/texbin/texhash

script:
  - /opt/texbin/pdflatex -halt-on-error Vol1.tex
  - /opt/texbin/pdflatex -halt-on-error Vol2.tex
  - /opt/texbin/pdflatex -halt-on-error Vol3.tex
  - /opt/texbin/pdflatex -halt-on-error Vol4.tex
  - /opt/texbin/pdflatex -halt-on-error ExtraLabs.tex
  - /opt/texbin/pdflatex -halt-on-error InstructorNotes.tex
  - python travis_post.py
