# .travis.yml

# This script is used for testing using Travis
# It is intended to work on their VM set up: Ubuntu 12.04 LTS
# A minimal current TL is installed adding only the packages that are
# required

language: python

python:
  - 2.7

env:
  # - PATH: /opt/texbin:/usr/local/texlive/2016/bin/x86_64-linux:$PATH
  - PATH: /tmp/texlive/bin/x86_64-linux:$PATH

before_install:
  - python travis_pre.py

install: # Download and install a vanilla TexLive
  - wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  - tar -xzf install-tl-unx.tar.gz # -C ./temp_texlive # --strip-components=1
  - cd install-tl-20*
  - sudo ./install-tl -profile=../.nmc.profile
  - sudo /usr/local/texlive/20*/bin/x86_64-linux/tlmgr install algorithmicx
  - sudo /usr/local/texlive/20*/bin/x86_64-linux/tlmgr update --self --all --no-auto-install
  # - tlmgr update --self --all --no-auto-install
  # - sudo /usr/local/texlive/2014/bin/x86_64-linux/tlmgr install iftex
  # - sudo /usr/local/texlive/2014/bin/x86_64-linux/texhash
  - cd ../

script:
  - /usr/local/texlive/20*/bin/x86_64-linux/pdflatex Vol1.tex
  - /usr/local/texlive/20*/bin/x86_64-linux/pdflatex Vol2.tex
  - /usr/local/texlive/20*/bin/x86_64-linux/pdflatex Vol3.tex
  - /usr/local/texlive/20*/bin/x86_64-linux/pdflatex Vol4.tex
  - /usr/local/texlive/20*/bin/x86_64-linux/pdflatex ExtraLabs.tex
  - /usr/local/texlive/20*/bin/x86_64-linux/pdflatex InstructorNotes.tex
  - python travis_post.py

