# .travis.yml

language: python

python:
  - 2.7

env:
  - PATH: /tmp/texlive/bin/x86_64-linux:$PATH

before_install:
  - python travis_pre.py

install: # Download and install a vanilla TexLive
  - wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  - tar -xzf install-tl-unx.tar.gz
  - cd install-tl-20*
  - sudo ./install-tl -profile=../.nmc.profile
  - sudo /usr/local/texlive/20*/bin/x86_64-linux/tlmgr install algorithmicx
  - sudo /usr/local/texlive/20*/bin/x86_64-linux/tlmgr install algorithms
  - sudo /usr/local/texlive/20*/bin/x86_64-linux/tlmgr update --self --all --no-auto-install
  - cd ../

script:
  - /usr/local/texlive/20*/bin/x86_64-linux/pdflatex Vol1.tex
  - /usr/local/texlive/20*/bin/x86_64-linux/pdflatex Vol2.tex
  - /usr/local/texlive/20*/bin/x86_64-linux/pdflatex Vol3.tex
  - /usr/local/texlive/20*/bin/x86_64-linux/pdflatex Vol4.tex
  - /usr/local/texlive/20*/bin/x86_64-linux/pdflatex ExtraLabs.tex
  - /usr/local/texlive/20*/bin/x86_64-linux/pdflatex InstructorNotes.tex
  - python travis_post.py

